const shopAnalysis = {
  crawlSource: "smartstore",
  domain: "/smartstore.naver.com/",
  analysis: {
    kind: "category-all",
    areaShopAllProductsUrl: {
      shopAllProductsUrlForm: "${shopUrl}/category/ALL",
      waitSec: 0.5,
    },
    areaGroupBox: {
      testAreaGroupBoxExpand: {
        testType: "tryWork",
        areaCode: "area",
        areaExtract: "sendKeysEnter",
        areaType: "css",
        area: "._3ryPAjhmjZ",
        resultKind: "obj",
        waitSec: 0.5,
        isDel: "N",
      },
      areaGroupBoxExtractPreprocess: {
        areaCode: "script",
        scriptCommand:
          "document.querySelectorAll('._3PK0aGa3Hc').forEach(el=>el.remove())",
        waitSec: 0.2,
        isDel: "N",
      },
      areaGroupBoxExtractGroupBtnEles: {
        areaCode: "area",
        areaExtract: "findElements",
        areaType: "css",
        area: "._3HQCww4jR6",
        resultKind: "list",
        waitSec: 0,
        isDel: "N",
      },
      areaGroup: {
        testGroupIsExcludeGroup: {
          testType: "compareEq",
          areaCode: "area",
          areaExtract: "text",
          areaType: "css",
          area: "itself",
          compareTarget: "전체상품",
          resultKind: "obj",
          waitSec: 0,
          isDel: "N",
        },
        areaGroupExtractName: {
          areaCode: "area",
          areaExtract: "text",
          areaType: "css",
          area: "itself",
          resultKind: "obj",
          waitSec: 0,
          isDel: "N",
        },
      },
    },
    areaPaging: {
      kind: "number-section",
      testAreaPagingExist: {
        testType: "try",
        areaCode: "area",
        areaExtract: "findElement",
        areaType: "css",
        area: ".fAUKm1ewwo",
        resultKind: "obj",
        waitSec: 0,
        isDel: "N",
      },
      areaPagingExtractPrevBtnEle: {
        areaCode: "area",
        areaExtract: "findElement",
        areaType: "css",
        area: ".fAUKm1ewwo._2PB8-gs2tG",
        resultKind: "obj",
        waitSec: 0,
        isDel: "N",
      },
      areaPagingExtractNextBtnEle: {
        areaCode: "area",
        areaExtract: "findElement",
        areaType: "css",
        area: ".fAUKm1ewwo._2Ar8-aEUTq",
        resultKind: "obj",
        waitSec: 0,
        isDel: "N",
      },
      testPagingIsFirstPageSection: {
        areaCode: "area",
        testType: "compareEq",
        areaExtract: "attrCustomTarget",
        areaType: "css",
        area: ".fAUKm1ewwo._2PB8-gs2tG",
        attrTarget: "aria-hidden",
        compareTarget: "true",
        resultKind: "obj",
        waitSec: 0,
        isDel: "N",
      },
      testPagingIsLastPageSection: {
        areaCode: "area",
        testType: "compareEq",
        areaExtract: "attrCustomTarget",
        areaType: "css",
        area: ".fAUKm1ewwo._2Ar8-aEUTq",
        attrTarget: "aria-hidden",
        compareTarget: "true",
        resultKind: "obj",
        waitSec: 0,
        isDel: "N",
      },
      areaPagingExtractPageNumBtnEles: {
        areaCode: "area",
        areaExtract: "findElements",
        areaType: "css",
        area: ".UWN4IvaQza",
        resultKind: "list",
        waitSec: 0,
        isDel: "N",
      },
      areaPageNum: {
        areaPageNumMove: {
          areaCode: "area",
          areaExtract: "sendKeysEnter",
          areaType: "css",
          area: "itself",
          resultKind: "obj",
          waitSec: 2,
          isDel: "N",
        },
        areaPageNumExtractItemEles: {
          areaCode: "area",
          areaExtract: "findElements",
          areaType: "css",
          area: "._3BkKgDHq3l",
          resultKind: "list",
          waitSec: 0.5,
          isDel: "N",
        },
        areaPageNumItem: {
          areaPageNumItemOpen: {
            areaCode: "area",
            areaExtract: "sendKeysEnter",
            areaType: "css",
            area: "itself",
            resultKind: "obj",
            waitSec: 1,
            isDel: "N",
          },
          areaPageNumItemClose: {
            areaCode: "script",
            scriptCommand: "history.back();",
            waitSec: 2,
            isDel: "N",
          },
        },
      },
    },
    areaItem: {
      currency: "KRW",
      isScrollDownFullPage: "Y",
      waitSec: 0.5,
      testAreaItemExist: {
        testType: "try",
        areaCode: "area",
        areaExtract: "findElement",
        areaType: "css",
        area: "._3oDjSvLwq9",
        resultKind: "obj",
        waitSec: 0,
        isDel: "N",
      },
      testAreaItemSoldOut: {
        testType: "try",
        areaCode: "area",
        areaExtract: "findElement",
        areaType: "css",
        area: "._2BQ-WF2QUb",
        resultKind: "obj",
        waitSec: 0,
        isDel: "N",
      },
      areaItemExtractName: {
        areaCode: "area",
        areaExtract: "text",
        areaType: "css",
        area: ".CxNYUPvHfB",
        resultKind: "obj",
        waitSec: 0,
        isDel: "N",
      },
      areaItemExtractThumbImg: {
        areaCode: "area",
        areaExtract: "attrSrc",
        areaType: "css",
        area: "._23RpOU6xpc img",
        resultKind: "obj",
        waitSec: 0,
        isDel: "N",
      },
      areaItemExtractPrice: {
        areaCode: "area",
        areaExtract: "text",
        areaType: "css",
        area: ".aICRqgP9zw ._1LY7DqCnwR",
        resultKind: "obj",
        waitSec: 0,
        isDel: "N",
      },
      areaItemExtractOriginPrice: {
        areaCode: "area",
        areaExtract: "text",
        areaType: "css",
        area: ".Xdhdpm0BD9 ._1LY7DqCnwR",
        resultKind: "obj",
        waitSec: 0,
        isDel: "N",
      },
      areaItemExtractShopCategoryEles: {
        areaCode: "area",
        areaExtract: "findElements",
        areaType: "css",
        area: "._3bYOrjr_7d",
        resultKind: "list",
        waitSec: 0.2,
        isDel: "N",
      },
      areaItemMainContainer: {
        areaCode: "area",
        areaExtract: "findElements",
        areaType: "css",
        // area: "div.se-main-container>div:not(.se-placesMap)",
        area: "div#INTRODUCE",
        resultKind: "list",
        waitSec: 0,
        isDel: "N",
        areaItemDetailImgEles: {
          areaCode: "area",
          areaExtract: "findElements",
          areaType: "css",
          area: "child",
          childArea:
            "img:is(img:not(._25CKxIKjAk):is(.se-image-resource,.se-inline-image-resource), img[data-src]:not([usemap]):not([alt])",
          resultKind: "list",
          waitSec: 0,
          isDel: "N",
        },
      },

      areaItemOption: {
        areaOptions: [],
        scripts: {
          areaOptionFocusOut: {
            areaCode: "script",
            scriptCommand: `document.querySelector('.CxNYUPvHfB').click();`,
            waitSec: 0.2,
            isDel: "N",
          },
          areaDoAfterChooseOptionItem: {
            areaCode: "script",
            scriptCommand: `document.querySelector('.CxNYUPvHfB').click();`,
            waitSec: 0.2,
            isDel: "N",
          },
          areaDoAfterCrawlOptionItemPrice: {
            areaCode: "script",
            scriptCommand: ``,
            waitSec: 0.2,
            isDel: "Y",
          },
        },
      },
    },
  },
};

module.exports = shopAnalysis;
